name: Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Extract version
        id: get_version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build All Projects
        run: dotnet build ./src/MaksimShimshon.Mediator.slnx  --configuration Release

